"""Reproducibility.

The project's claim that a seed reproduces a run is load-bearing: the what-if lab
compares seed-matched pairs, and replay windows are generated by re-running stored
scenarios in a second pass. If seeding were not exact, both would be wrong.

The subtlety worth guarding: iterating a Python ``set`` consumes random draws in
hash order, which varies between processes. That defect was present and these
tests exist because of it, so the hash-order test is not hypothetical.
"""

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

from apex.batch import build_run
from apex.circuits import get_track
from apex.drivers import build_roster, perturb
from apex.engine import RaceEngine
from apex.environment import make_environment
from apex.models import Scenario
from apex.scenario import ScenarioSpace, sample, scenario_from_dict

BACKEND = Path(__file__).resolve().parents[1]


def _digest(arr) -> str:
    return hashlib.sha1(
        np.ascontiguousarray(arr, dtype=np.float64).tobytes()).hexdigest()


def _scenario(seed=483921, duration=25.0, cars=22):
    return sample(seed, ScenarioSpace(),
                  pin=dict(n_cars=cars, weather="WET", traffic_density=0.7,
                           duration=duration))


def test_same_seed_same_trajectories():
    sc = _scenario()
    r1, _ = build_run(sc)
    r2, _ = build_run(scenario_from_dict(sc.to_dict()))
    assert _digest(r1.traj_s) == _digest(r2.traj_s)
    assert _digest(r1.traj_v) == _digest(r2.traj_v)
    assert _digest(r1.traj_d) == _digest(r2.traj_d)
    assert len(r1.conflicts) == len(r2.conflicts)
    assert r1.n_collisions == r2.n_collisions
    assert r1.error_counts == r2.error_counts


def test_different_seed_different_trajectories():
    r1, _ = build_run(_scenario(seed=1))
    r2, _ = build_run(_scenario(seed=2))
    assert _digest(r1.traj_v) != _digest(r2.traj_v)


def test_scenario_sampling_is_reproducible():
    a, b = sample(4242, ScenarioSpace()), sample(4242, ScenarioSpace())
    assert a.config_fingerprint() == b.config_fingerprint()
    assert a.field_mix == b.field_mix
    assert a.environment.grip == b.environment.grip


def test_reproducible_across_processes_with_randomised_hash_seed():
    """A fresh interpreter with a different PYTHONHASHSEED must agree.

    This is the regression test for set-ordered RNG consumption. Two subprocesses
    are launched with explicitly different hash seeds; if any code path iterates a
    set while drawing randoms, their digests diverge.
    """
    script = (
        "import sys, hashlib, numpy as np;"
        f"sys.path.insert(0, {str(BACKEND)!r});"
        "from apex.scenario import sample, ScenarioSpace;"
        "from apex.batch import build_run;"
        "sc = sample(483921, ScenarioSpace(), pin=dict(n_cars=22, weather='WET',"
        " traffic_density=0.7, duration=25.0));"
        "r,_ = build_run(sc);"
        "print(hashlib.sha1(np.ascontiguousarray(r.traj_v, dtype=np.float64)"
        ".tobytes()).hexdigest());"
        "print(len(r.conflicts), r.n_collisions, r.n_off_track)"
    )
    outs = []
    for hashseed in ("0", "12345"):
        env = dict(os.environ, PYTHONHASHSEED=hashseed)
        res = subprocess.run([sys.executable, "-c", script], capture_output=True,
                             text=True, env=env, timeout=300)
        assert res.returncode == 0, res.stderr
        outs.append(res.stdout.strip())
    assert outs[0] == outs[1], (
        "run diverged under a different PYTHONHASHSEED — something is consuming "
        f"random draws in hash order:\n{outs[0]}\n{outs[1]}"
    )


def test_perturbation_preserves_identity():
    """Randomness perturbs a personality; it does not replace it."""
    base = build_roster(22)
    rosters = [perturb(base, np.random.default_rng(s)) for s in range(40)]
    for i, p in enumerate(base):
        aggs = np.array([r[i].aggression for r in rosters])
        # The mean stays near the profile and the spread stays small.
        assert abs(aggs.mean() - p.aggression) < 0.03
        assert aggs.std() < 0.08
        assert all(r[i].archetype == p.archetype for r in rosters)


def test_consistent_driver_varies_less_than_unpredictable_one():
    base = build_roster(22)
    hc = next(i for i, p in enumerate(base) if p.archetype == "HIGH_CONSISTENCY")
    un = next(i for i, p in enumerate(base) if p.archetype == "UNPREDICTABLE")
    rosters = [perturb(base, np.random.default_rng(s)) for s in range(60)]
    spread_hc = np.std([r[hc].line_change_tendency for r in rosters])
    spread_un = np.std([r[un].line_change_tendency for r in rosters])
    assert spread_un > 2.0 * spread_hc


def test_intervention_preserves_the_seed():
    from apex.scenario import with_intervention
    base = _scenario()
    iv = with_intervention(base, dict(overtake_threshold_delta=0.15))
    assert iv.seed == base.seed
    assert iv.config_fingerprint() != base.config_fingerprint()
    assert iv.field_mix == base.field_mix
